INSERT INTO `lingala` (`english`, `lingala`) VALUES('I', 'ngáí, na-');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('you (singular)', 'yɔ̌, o-');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('he', 'yě, a- *(person)*, e- *(thing)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('we', 'bísó, to-');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('you (plural)', 'bínó, bo-');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('they', 'bangó, [1] ba- *(persons)*, e-/i- *(things)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('this', 'óyo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('that', 'wâná');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('here', 'áwa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('there', 'kúná, wâná');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('who', 'náni *(interrogative)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('what', 'níni *(interrogative)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('where', 'wápi *(interrogative)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('when', 'ntángo *(interrogative)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('how', 'bóní *(interrogative)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('not', '… tɛ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('all', 'nyɛ́, tû');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('many', 'míngi');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('some', 'bɔ̌kɔ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('few', 'mɔkɛ́mɔkɛ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('other', 'mosúsu, -súsu');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('one', 'mɔ̌kɔ, -ɔ̌kɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('two', 'míbalé, -íbalé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('three', 'mísáto, -ísáto');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('four', 'mínei, -ínei');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('five', 'mítánɔ, -ítánɔ, mpáta');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('big', 'monɛ́nɛ, -nɛ́nɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('long', 'monɛ́nɛ, -nɛ́nɛ, -laí');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('wide', '-laí');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('thick', 'monɛ́nɛ, -nɛ́nɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('heavy', 'bozitó, kiló, molito');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('small', 'mokɛ́, -kɛ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('short', 'mokúsé, -kúsé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('narrow', 'mokɛ́, -kɛ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('thin', 'mokɛ́, -kɛ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('woman', 'mwǎsí');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('man (adult male)', 'mobáli');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('man (human being)', 'moto');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('child', 'mwǎna');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('wife', 'bolóngani, mwǎsí');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('husband', 'bolóngani, mobáli');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('mother', 'mamá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('father', 'tatá, papá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('animal', 'nyama');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('fish', 'mbísi');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('bird', 'ndɛkɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('dog', 'mbwá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('louse', 'lonsili');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('snake', 'nyóka');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('worm', 'mpambó, mósɔ́pi, limpiká');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('tree', 'nzeté, mweté');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('forest', 'zámba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('stick', 'nzeté');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('fruit', 'mbuma');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('seed', 'nyǎ, mbóto, bɔpɔ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('leaf', 'nkásá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('root', 'ntína');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('bark (of a tree)', 'lomposo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('flower', 'fulɛ́lɛ, lómbé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('grass', 'litíti');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('rope', 'nsi nga, moniɔlɔ́lɔ, likósi');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('skin', 'lomposo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('meat', 'monsuni');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('blood', 'makilá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('bone', 'monkúwa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('fat (noun)', 'mafúta');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('egg', 'likeí, líki');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('horn', 'liséké, boséba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('tail', 'mokɔndɔ́, mokíla');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('feather', 'lonsálá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('hair', 'nsúki');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('head', 'motó');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('ear', 'litói');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('eye', 'líso');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('nose', 'zólo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('mouth', 'mɔnɔkɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('tooth', 'líno');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('tongue (organ)', 'lolému');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('fingernail', 'linzáka');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('foot', 'mopendé, lokolo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('leg', 'lokolo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('knee', 'libɔ́lɔ́ngɔ́, libɔ́ngɔ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('hand', 'lobɔ́kɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('wing', 'lipapú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('belly', 'libumu');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('guts', 'nsɔpɔ́');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('neck', 'nkíngó');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('back', 'mokɔngɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('breast', 'ntólo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('heart', 'motéma');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('liver', 'libale');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to drink', '-mɛlɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to eat', '-lía');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to bite', '-swâ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to suck', '-nyúnya, -núnga');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to spit', '-bwáka nsɔ́i');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to vomit', '-sánza');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to blow', '-pémela, -pɛpɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to breathe', '-péma');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to laugh', '-sɛkɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to see', '-mɔ́nɔ, -móna');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to hear', '-yóka');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to know', '-yéba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to think', '-bánza, -kanisa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to smell', '-núsa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to fear', '-bánga');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to sleep', '-lála');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to live', '-vánda');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to die', '-kúfa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to kill', '-boma');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to fight', '-bɛ́tɛnɛ, -bunda');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to hunt', '-bengana');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to hit', '-bɛ́tɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to cut', '-kátakata, -káta');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to split', '-pasola');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to scratch', '-kóta, -nyaka, -kpaka, -kpala');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to dig', '-tímola');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to swim', '-nyanya, -túnga');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to fly', '-pimbwa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to walk', '-támbola');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to come', '-yâ, -yáa, -úta');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to lie (as in a bed)', '-lálisana *(action)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to sit', '-vánda, -kisa *(action)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to stand', '-lamuka, -télema *(action)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to turn (intransitive)', '-balula');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to fall', '-kpâ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to give', '-pésa, -kaba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to hold', '-kamata');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to squeeze', '-kangisa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to rub', '-bísa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to wash', '-sukola');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to wipe', '-pangwisa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to pull', '-bénda');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to push', '-tɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to throw', '-bwáka');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to tie', '-kanga, -zínga, -línga');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to sew', '-sɔnɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to count', '-tánga');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to say', '-loba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to sing', '-yémba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to play', '-sakana, -sana');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to float', '-tetwa, -tepa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to flow', '-támbola');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to swell', '-vímba');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('sun', 'mói');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('moon', 'sánzá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('star', 'monzɔ́tɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('water', 'mái');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('rain', 'mbúla');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('river', 'mái, ebale');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('lake', 'etíma, nzálé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('sea', 'mbú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('salt', 'móngwa, mókpa');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('stone', 'libángá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('sand', 'zɛ́lɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('dust', 'putulú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('earth', 'mabelé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('cloud', 'lipata');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('fog', 'londendé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('sky', 'likoló');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('wind', 'mompɛpɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('smoke', 'mólinga');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('fire', 'mɔ́tɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('ash', 'putulú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('to burn', '-pela, -zíka');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('road', 'balabála, nzɛlá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('mountain', 'ngómbá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('red', '-táné');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('green', '-bésu');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('yellow', '-táne');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('white', 'mpɛ́mbɛ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('black', 'molílí, -índo');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('night', 'butú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('day', 'mokɔlɔ, mói');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('year', 'mbúla, mobú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('warm', '-tɔkɔ *(to warm up)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('cold', 'mpíɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('full', 'má, mɛké');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('new', 'sika');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('old', 'kala');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('good', 'kitɔ́kɔ, malámu');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('bad', 'mabé');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('rotten', '-pɔlɔ *(to go rotten)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('dirty', '-bébisa *(to make dirty)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('straight', 'alimá');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('round', 'kílíkílí');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('sharp (as a knife)', '-pela');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('dull (as a knife)', '-túnú');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('smooth', 'patátálú, sɛ́lisɛ́li');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('wet', 'pɔlɔ');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('dry', '-kauka *(to dry)*');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('correct', 'alimá, malongá, sémba, sɛló');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('near', 'mpɛmbɛ́ni');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('far', 'mosíká');
INSERT INTO `lingala` (`english`, `lingala`) VALUES('right', 'a mobáli');